<a href="https://colab.research.google.com/github/harideegee/dlgenai_iitmbs/blob/main/week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Environment Setup

In [1]:
import torch
import matplotlib.pyplot as plt
import numpy as np
import matplotlib

print(torch.__version__)
print(np.__version__)
print(matplotlib.__version__)

print(f"CUDA Availability: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA Current Device: {torch.cuda.current_device()}")
    print(f"CUDA Device Name: {torch.cuda.get_device_name(0)}")
    print(f"CUDA Device Properties: {torch.cuda.get_device_properties(0)}")
    print(f"CUDA Device Capabilities: {torch.cuda.get_device_capability(0)}")



2.11.0+cu128
2.0.2
3.10.0
CUDA Availability: True
CUDA Current Device: 0
CUDA Device Name: Tesla T4
CUDA Device Properties: _CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=14912MB, multi_processor_count=40, uuid=d2a3fc48-e56f-0ee2-cf9a-d7bb777cb20b, pci_bus_id=0, pci_device_id=4, pci_domain_id=0, L2_cache_size=4MB)
CUDA Device Capabilities: (7, 5)


# Tensor Creation Methods

In [2]:
# 0 dimensional tensors
scalar_tensor = torch.tensor(7)

# 1 dimensional tensors
vector_tensor = torch.tensor([1, 2, 3, 4, 5])

# 2 dimensional tensors
matrix_tensor = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# 3 dimensional tensors
tensor_3d = torch.tensor([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

In [3]:
# Scalar
print(f"Tensor: {scalar_tensor}, Shape: {scalar_tensor.shape}, Dimension: {scalar_tensor.ndim}")

# Vector
print(f"Tensor: {vector_tensor}, Shape: {vector_tensor.shape}, Dimension: {vector_tensor.ndim}")

# Matrix
print(f"Tensor: {matrix_tensor}, Shape: {matrix_tensor.shape}, Dimension: {matrix_tensor.ndim}")

# 3D Tensor
print(f"Tensor: {tensor_3d}, Shape: {tensor_3d.shape}, Dimension: {tensor_3d.ndim}")

Tensor: 7, Shape: torch.Size([]), Dimension: 0
Tensor: tensor([1, 2, 3, 4, 5]), Shape: torch.Size([5]), Dimension: 1
Tensor: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), Shape: torch.Size([3, 3]), Dimension: 2
Tensor: tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]), Shape: torch.Size([2, 2, 2]), Dimension: 3


## Datatype Specification

In [4]:
# Float tensor (default is float32)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

# Double-precision float tensor
double_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)

# Integer tensor
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

# Long integer tensor
long_tensor = torch.tensor([1, 2, 3], dtype=torch.int64)

# Boolean tensor
bool_tensor = torch.tensor([True, False, True], dtype=torch.bool)

# Print data types and memory usage
print(f"Float32 tensor: {float_tensor.dtype}, bytes per element: {float_tensor.element_size()}")
print(f"Float64 tensor: {double_tensor.dtype}, bytes per element: {double_tensor.element_size()}")
print(f"Int32 tensor: {int_tensor.dtype}, bytes per element: {int_tensor.element_size()}")
print(f"Int64 tensor: {long_tensor.dtype}, bytes per element: {long_tensor.element_size()}")
print(f"Boolean tensor: {bool_tensor.dtype}, bytes per element: {bool_tensor.element_size()}")

Float32 tensor: torch.float32, bytes per element: 4
Float64 tensor: torch.float64, bytes per element: 8
Int32 tensor: torch.int32, bytes per element: 4
Int64 tensor: torch.int64, bytes per element: 8
Boolean tensor: torch.bool, bytes per element: 1


## Creating Tensors from NumPy Arrays

In [9]:
np_array = np.array([[1, 2, 3], [4, 5, 6]])

tensor_from_numpy = torch.from_numpy(np_array)

print(f"Numpy Array: {np_array}, dtype: {np_array.dtype}")
print(f"Tensor from Numpy: {tensor_from_numpy}, dtype: {tensor_from_numpy.dtype}")

np_array[0, 0] = 100
print("\nAfter Modifying")
print(f"Numpy Array: {np_array}")
print(f"Tensor from Numpy: {tensor_from_numpy}")

Numpy Array: [[1 2 3]
 [4 5 6]], dtype: int64
Tensor from Numpy: tensor([[1, 2, 3],
        [4, 5, 6]]), dtype: torch.int64

After Modifying
Numpy Array: [[100   2   3]
 [  4   5   6]]
Tensor from Numpy: tensor([[100,   2,   3],
        [  4,   5,   6]])


## Creating empty, one and zero tensors

In [13]:
zeroes_tensor = torch.zeros(3, 3)
ones_tensor = torch.ones(2, 4)
empty_tensor = torch.empty(2, 2)
filled_tensor = torch.full((3, 2), 42)

print(f"Zeroes Tensor: \n{zeroes_tensor}")
print(f"Ones Tensor: \n{ones_tensor}")
print(f"Empty Tensor: \n{empty_tensor}")
print(f"Filled Tensor: \n{filled_tensor}")

Zeroes Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Ones Tensor: 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Empty Tensor: 
tensor([[0., 0.],
        [0., 0.]])
Filled Tensor: 
tensor([[42, 42],
        [42, 42],
        [42, 42]])


## Sequential Tensors

In [17]:
range_tensor = torch.arange(0, 10)
step_tensor = torch.arange(0, 10, 2)
linear_tensor = torch.linspace(0, 1, 5)
log_tensor = torch.logspace(1, 4, 5)

print(f"Range tensor: {range_tensor}")
print(f"Step tensor: {step_tensor}")
print(f"Linear tensor: {linear_tensor}")
print(f"Logarithmic tensor: {log_tensor}")

Range tensor: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Step tensor: tensor([0, 2, 4, 6, 8])
Linear tensor: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
Logarithmic tensor: tensor([   10.0000,    56.2341,   316.2278,  1778.2794, 10000.0000])


## Identity Matrices

In [19]:
identity_matrix = torch.eye(3)
non_square_identity = torch.eye(2, 4)

print(f"3x3 Identity Matrix: \n{identity_matrix}")
print(f"2x4 Identity-like Matrix: \n{non_square_identity}")

3x3 Identity Matrix: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
2x4 Identity-like Matrix: 
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.]])


## Diagonal Matrices

In [21]:
vector = torch.tensor([1, 2, 3])
diagonal_matrix = torch.diag(vector)

matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
extracted_diagonal = torch.diag(matrix)

print(f"Vector: {vector}")
print(f"Diagonal Matrix: \n{diagonal_matrix}")
print(f"\nOriginal Matrix: \n{matrix}")
print(f"Extracted Diagonal: {extracted_diagonal}")

Vector: tensor([1, 2, 3])
Diagonal Matrix: 
tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])

Original Matrix: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Extracted Diagonal: tensor([1, 5, 9])
